package theme

import androidx.compose.ui.graphics.Color

//    containerColor = Color(0xFF8f8fa6),
//    contentColor = Color(0xFF1C1C23)
//
internal val md_theme_light_primary =  Color(0xFF8f8fa6)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDF9E)
internal val md_theme_light_onPrimaryContainer = Color(0xFF261A00)
internal val md_theme_light_secondary = Color(0xFF6B5D3F)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFF5E0BB)
internal val md_theme_light_onSecondaryContainer = Color(0xFF241A04)
internal val md_theme_light_tertiary = Color(0xFF4A6547)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFCCEBC4)
internal val md_theme_light_onTertiaryContainer = Color(0xFF072109)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFFFF)
internal val md_theme_light_onBackground = Color(0xFF1E1B16)
internal val md_theme_light_surface = Color(0xFFFFFFFF)
internal val md_theme_light_onSurface = Color(0xFF1E1B16)
internal val md_theme_light_surfaceVariant = Color(0xFFEDE1CF)
internal val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
internal val md_theme_light_outline = Color(0xFF7F7667)
internal val md_theme_light_inverseOnSurface = Color(0xFFF7EFE7)
internal val md_theme_light_inverseSurface = Color(0xFF33302A)
internal val md_theme_light_inversePrimary = Color(0xFFF2BF48)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF795900)
internal val md_theme_light_outlineVariant = Color(0xFFD0C5B4)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF8f8fa6)
internal val md_theme_dark_onPrimary = Color(0xFF3F2E00)
internal val md_theme_dark_primaryContainer = Color(0xFF5B4300)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF9E)
internal val md_theme_dark_secondary = Color(0xFFD8C4A0)
internal val md_theme_dark_onSecondary = Color(0xFF3B2F15)
internal val md_theme_dark_secondaryContainer = Color(0xFF52452A)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFF5E0BB)
internal val md_theme_dark_tertiary = Color(0xFFB0CFAA)
internal val md_theme_dark_onTertiary = Color(0xFF1D361C)
internal val md_theme_dark_tertiaryContainer = Color(0xFF334D31)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFCCEBC4)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1C1C23)
internal val md_theme_dark_onBackground = Color(0xFFE9E1D8)
internal val md_theme_dark_surface = Color(0xFF1C1C23)
internal val md_theme_dark_onSurface = Color(0xFFE9E1D8)
internal val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
internal val md_theme_dark_outline = Color(0xFF998F80)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
internal val md_theme_dark_inverseSurface = Color(0xFFE9E1D8)
internal val md_theme_dark_inversePrimary = Color(0xFF795900)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFF2BF48)
internal val md_theme_dark_outlineVariant = Color(0xFF4D4639)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF785900)
internal val mycustompick = Color(0xFFEEDD82)
internal val light_mycustompick = Color(0xFF6B5F00)
internal val light_onmycustompick = Color(0xFFFFFFFF)
internal val light_mycustompickContainer = Color(0xFFF9E366)
internal val light_onmycustompickContainer = Color(0xFF211C00)
internal val dark_mycustompick = Color(0xFFDCC74D)
internal val dark_onmycustompick = Color(0xFF383000)
internal val dark_mycustompickContainer = Color(0xFF514700)
internal val dark_onmycustompickContainer = Color(0xFFF9E366)